name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 2.1
      - name: Publish python package
        run: poetry version ${{ steps.vars.outputs.tag }} && poetry config pypi-token.pypi ${{ secrets.PYPI_API_KEY }} && poetry build  && poetry publish
      - name: Auto commit pyproject.toml
        uses: EndBug/add-and-commit@v4.4.0
        with:
          add: pyproject.toml
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
